" 
" Tips/Tricks from SO: http://stackoverflow.com/questions/164847/what-is-in-your-vimrc
" 

filetype on
filetype plugin on
syntax enable

" Cool tab completion stuff
" tips: http://www.dickscheid.net/2011/04/17-vimsWildmenu/
set wildmenu
set wildmode=list:longest,full

" Turn on spell checking, but off by default
if version >= 700
   set spl=en spell
   set nospell
endif

" Who doesn't like autoindent?
set cindent

" Spaces are better than a tab character
set expandtab
set smarttab

" Who wants an 8 character tab?  Not me!
set shiftwidth=4
set softtabstop=4


" Cool tab completion stuff
set wildmenu
set wildmode=list:longest,full

" Line Numbers PWN!
set number

" Ignore cases in searches
set ignorecase

" if search pattern contains an upper case char, it will do a case-sensitive
" search
set smartcase

colorscheme inkpot

"Status line gnarliness
set laststatus=2
set statusline=%F%m%r%h%w\ (%{&ff}){%Y}\ [%l,%v][%p%%]

"Working/Backup Directories
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

" Automatically change working dir. to the one the file is in
"set autochdir

" SuperTab Configuration
let g:SuperTabDefaultCompletionType = "<C-X><C-O>"
let g:SuperTabDefaultCompletionType = "context"

" Fuzzy Finder shortcuts
nmap <leader>f :FufFile **/*<CR>
nmap <leader>b :FufBuffer<CR>
nmap <leader>t :FufTag<CR>
nmap <leader>l :FufLine<CR>

" Pathogen
" here's why: http://tammersaleh.com/posts/the-modern-vim-config-with-pathogen
call pathogen#infect()
call pathogen#helptags()

" Settings for delimitMate
let delimitMate_expand_cr = 1
